name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            -  run: cd redis
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -a -c --sourceroot
              env:
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  URL: ${{ secrets.URL }}
                  URL_ID: ${{ secrets.URL_ID }}
            - name: what dir 3
              run: pwd
